// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: proto/camionProto.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AskForPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo string `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
}

func (x *AskForPack) Reset() {
	*x = AskForPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_camionProto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskForPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForPack) ProtoMessage() {}

func (x *AskForPack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_camionProto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForPack.ProtoReflect.Descriptor instead.
func (*AskForPack) Descriptor() ([]byte, []int) {
	return file_proto_camionProto_proto_rawDescGZIP(), []int{0}
}

func (x *AskForPack) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

type SendPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete string `protobuf:"bytes,1,opt,name=idPaquete,proto3" json:"idPaquete,omitempty"`
	Tipo      string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre    string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor     int64  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen    string `protobuf:"bytes,5,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino   string `protobuf:"bytes,6,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *SendPack) Reset() {
	*x = SendPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_camionProto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPack) ProtoMessage() {}

func (x *SendPack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_camionProto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPack.ProtoReflect.Descriptor instead.
func (*SendPack) Descriptor() ([]byte, []int) {
	return file_proto_camionProto_proto_rawDescGZIP(), []int{1}
}

func (x *SendPack) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *SendPack) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *SendPack) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *SendPack) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *SendPack) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *SendPack) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type ReportDelivery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete string `protobuf:"bytes,1,opt,name=idPaquete,proto3" json:"idPaquete,omitempty"`
	Entregado bool   `protobuf:"varint,2,opt,name=entregado,proto3" json:"entregado,omitempty"`
	Intentos  int64  `protobuf:"varint,3,opt,name=intentos,proto3" json:"intentos,omitempty"`
}

func (x *ReportDelivery) Reset() {
	*x = ReportDelivery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_camionProto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDelivery) ProtoMessage() {}

func (x *ReportDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_camionProto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDelivery.ProtoReflect.Descriptor instead.
func (*ReportDelivery) Descriptor() ([]byte, []int) {
	return file_proto_camionProto_proto_rawDescGZIP(), []int{2}
}

func (x *ReportDelivery) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *ReportDelivery) GetEntregado() bool {
	if x != nil {
		return x.Entregado
	}
	return false
}

func (x *ReportDelivery) GetIntentos() int64 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

type ReportOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ReportOk) Reset() {
	*x = ReportOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_camionProto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportOk) ProtoMessage() {}

func (x *ReportOk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_camionProto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportOk.ProtoReflect.Descriptor instead.
func (*ReportOk) Descriptor() ([]byte, []int) {
	return file_proto_camionProto_proto_rawDescGZIP(), []int{3}
}

func (x *ReportOk) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

var File_proto_camionProto_proto protoreflect.FileDescriptor

var file_proto_camionProto_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x20, 0x0a, 0x0a, 0x61, 0x73, 0x6b, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69,
	0x70, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x6f, 0x22, 0x68, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x64, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x64, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x22, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x71, 0x0a, 0x0e, 0x43, 0x61, 0x6d, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x2d, 0x0a, 0x07, 0x67, 0x65, 0x74,
	0x50, 0x61, 0x63, 0x6b, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x73, 0x6b,
	0x46, 0x6f, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x73, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x4f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_camionProto_proto_rawDescOnce sync.Once
	file_proto_camionProto_proto_rawDescData = file_proto_camionProto_proto_rawDesc
)

func file_proto_camionProto_proto_rawDescGZIP() []byte {
	file_proto_camionProto_proto_rawDescOnce.Do(func() {
		file_proto_camionProto_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_camionProto_proto_rawDescData)
	})
	return file_proto_camionProto_proto_rawDescData
}

var file_proto_camionProto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_camionProto_proto_goTypes = []interface{}{
	(*AskForPack)(nil),     // 0: proto.askForPack
	(*SendPack)(nil),       // 1: proto.sendPack
	(*ReportDelivery)(nil), // 2: proto.reportDelivery
	(*ReportOk)(nil),       // 3: proto.reportOk
}
var file_proto_camionProto_proto_depIdxs = []int32{
	0, // 0: proto.CamionDelivery.getPack:input_type -> proto.askForPack
	2, // 1: proto.CamionDelivery.report:input_type -> proto.reportDelivery
	1, // 2: proto.CamionDelivery.getPack:output_type -> proto.sendPack
	3, // 3: proto.CamionDelivery.report:output_type -> proto.reportOk
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_camionProto_proto_init() }
func file_proto_camionProto_proto_init() {
	if File_proto_camionProto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_camionProto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskForPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_camionProto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_camionProto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportDelivery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_camionProto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_camionProto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_camionProto_proto_goTypes,
		DependencyIndexes: file_proto_camionProto_proto_depIdxs,
		MessageInfos:      file_proto_camionProto_proto_msgTypes,
	}.Build()
	File_proto_camionProto_proto = out.File
	file_proto_camionProto_proto_rawDesc = nil
	file_proto_camionProto_proto_goTypes = nil
	file_proto_camionProto_proto_depIdxs = nil
}
