// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CamionDeliveryClient is the client API for CamionDelivery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CamionDeliveryClient interface {
	GetPack(ctx context.Context, in *AskForPack, opts ...grpc.CallOption) (*SendPack, error)
	Report(ctx context.Context, in *ReportDelivery, opts ...grpc.CallOption) (*ReportOk, error)
}

type camionDeliveryClient struct {
	cc grpc.ClientConnInterface
}

func NewCamionDeliveryClient(cc grpc.ClientConnInterface) CamionDeliveryClient {
	return &camionDeliveryClient{cc}
}

func (c *camionDeliveryClient) GetPack(ctx context.Context, in *AskForPack, opts ...grpc.CallOption) (*SendPack, error) {
	out := new(SendPack)
	err := c.cc.Invoke(ctx, "/proto.CamionDelivery/getPack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *camionDeliveryClient) Report(ctx context.Context, in *ReportDelivery, opts ...grpc.CallOption) (*ReportOk, error) {
	out := new(ReportOk)
	err := c.cc.Invoke(ctx, "/proto.CamionDelivery/report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CamionDeliveryServer is the server API for CamionDelivery service.
// All implementations must embed UnimplementedCamionDeliveryServer
// for forward compatibility
type CamionDeliveryServer interface {
	GetPack(context.Context, *AskForPack) (*SendPack, error)
	Report(context.Context, *ReportDelivery) (*ReportOk, error)
	mustEmbedUnimplementedCamionDeliveryServer()
}

// UnimplementedCamionDeliveryServer must be embedded to have forward compatible implementations.
type UnimplementedCamionDeliveryServer struct {
}

func (UnimplementedCamionDeliveryServer) GetPack(context.Context, *AskForPack) (*SendPack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPack not implemented")
}
func (UnimplementedCamionDeliveryServer) Report(context.Context, *ReportDelivery) (*ReportOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedCamionDeliveryServer) mustEmbedUnimplementedCamionDeliveryServer() {}

// UnsafeCamionDeliveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CamionDeliveryServer will
// result in compilation errors.
type UnsafeCamionDeliveryServer interface {
	mustEmbedUnimplementedCamionDeliveryServer()
}

func RegisterCamionDeliveryServer(s *grpc.Server, srv CamionDeliveryServer) {
	s.RegisterService(&_CamionDelivery_serviceDesc, srv)
}

func _CamionDelivery_GetPack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskForPack)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamionDeliveryServer).GetPack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CamionDelivery/GetPack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamionDeliveryServer).GetPack(ctx, req.(*AskForPack))
	}
	return interceptor(ctx, in, info, handler)
}

func _CamionDelivery_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDelivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamionDeliveryServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CamionDelivery/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamionDeliveryServer).Report(ctx, req.(*ReportDelivery))
	}
	return interceptor(ctx, in, info, handler)
}

var _CamionDelivery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CamionDelivery",
	HandlerType: (*CamionDeliveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPack",
			Handler:    _CamionDelivery_GetPack_Handler,
		},
		{
			MethodName: "report",
			Handler:    _CamionDelivery_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/camionProto.proto",
}
